// Low-signal detection (R-002, spec 00 §Chunking #3): script-detectable `generated` only.
// Misclassification is expected and survivable — stubs still require a human mark (spec 00a).

const LOCKFILE_NAMES = new Set([
  'pnpm-lock.yaml',
  'package-lock.json',
  'npm-shrinkwrap.json',
  'yarn.lock',
  'bun.lock',
  'bun.lockb',
  'deno.lock',
  'cargo.lock',
  'composer.lock',
  'gemfile.lock',
  'poetry.lock',
  'uv.lock',
  'packages.lock.json',
  'paket.lock',
  'flake.lock',
  'go.sum',
]);

const GENERATED_EXTENSIONS = /\.(g|generated|designer)\.(cs|ts|js)$/;
const MINIFIED = /\.min\.(js|mjs|css)$|\.map$/;
const CONTENT_MARKERS = /<auto-generated|@generated|\bgenerated by\b|do not edit/i;
// `generated` as a delimited token, so `generated-types/` matches but `degenerated/` doesn't.
const GENERATED_DIR = /(^|[-_.])generated([-_.]|$)/i;
// en.po is the source catalog (translator comments, reviewer-relevant); translated locales
// are tool-managed (#10).
const SOURCE_LOCALE_PO = /^en([-_][a-z0-9]+)?\.po$/;

/**
 * Classifies a file as generated/low-signal from its path and (optionally) its first lines.
 * Returns the display reason for the stub badge, or undefined for normal files.
 */
export function classifyGenerated(filePath: string, headLines: string[] = []): string | undefined {
  const base = filePath.split('/').at(-1)?.toLowerCase() ?? '';
  if (LOCKFILE_NAMES.has(base)) return 'lockfile';
  if (base.endsWith('modelsnapshot.cs')) return 'migration snapshot';
  if (GENERATED_EXTENSIONS.test(base)) return 'generated';
  if (MINIFIED.test(base)) return 'minified';
  if (base.endsWith('.snap') || /(^|\/)__snapshots__\//.test(filePath)) return 'snapshot';
  if (base.endsWith('.po') && !SOURCE_LOCALE_PO.test(base)) return 'translations';
  if (filePath.split('/').slice(0, -1).some((dir) => GENERATED_DIR.test(dir))) return 'generated';
  if (CONTENT_MARKERS.test(headLines.slice(0, 5).join('\n'))) return 'generated';
  return undefined;
}
