import { describe, expect, it } from 'vitest';
import { classifyGenerated } from './classify.js';

describe('classifyGenerated', () => {
  it.each([
    ['pnpm-lock.yaml', 'lockfile'],
    ['frontend/package-lock.json', 'lockfile'],
    ['backend/packages.lock.json', 'lockfile'],
    ['Gemfile.lock', 'lockfile'],
    ['backend/LexData/Migrations/LexBoxDbContextModelSnapshot.cs', 'migration snapshot'],
    ['backend/LexCore/Resources.Designer.cs', 'generated'],
    ['backend/Api.g.cs', 'generated'],
    ['frontend/src/lib/gql/generated/graphql.ts', 'generated'],
    ['assets/vendor.min.js', 'minified'],
    ['dist/app.js.map', 'minified'],
    ['src/__snapshots__/render.test.ts.snap', 'snapshot'],
    ['frontend/viewer/src/lib/dotnet-types/generated-types/LcmCrdt/ActivitySort.ts', 'generated'],
    ['src/__generated__/schema.ts', 'generated'],
    ['frontend/viewer/src/locales/es.po', 'translations'],
    ['frontend/viewer/src/locales/fr.po', 'translations'],
  ])('flags %s as %s', (path, reason) => {
    expect(classifyGenerated(path)).toBe(reason);
  });

  it.each([
    'src/UserService.cs',
    'frontend/src/routes/+page.svelte',
    'package.json',
    'docs/lock-design.md',
    'src/generator.ts',
    'src/degenerated/thing.ts',
    'frontend/viewer/src/locales/en.po',
    'frontend/viewer/src/locales/en-US.po',
  ])('leaves %s alone', (path) => {
    expect(classifyGenerated(path)).toBeUndefined();
  });

  it('sniffs auto-generated markers in the first lines only', () => {
    expect(classifyGenerated('src/Api.cs', ['// <auto-generated />', 'namespace X;'])).toBe('generated');
    expect(classifyGenerated('src/api.ts', ['/* eslint-disable */', '// @generated by codegen'])).toBe('generated');
    expect(classifyGenerated('src/api.go', ['// Code generated by protoc. DO NOT EDIT.'])).toBe('generated');
    expect(
      classifyGenerated('src/ActivitySort.ts', ['//------------------', '// This code was generated by a Reinforced.Typings tool.']),
    ).toBe('generated');
    const markerPastWindow = [...Array.from({ length: 5 }, (_, i) => `line ${i}`), '// <auto-generated />'];
    expect(classifyGenerated('src/api.ts', markerPastWindow)).toBeUndefined();
  });
});
